#pragma once

// USB layouts built by this fork. Keep these values usable from both C and C++.
#define PICADE_USB_PROFILE_LEGACY       0
#define PICADE_USB_PROFILE_HID_ONLY     1
#define PICADE_USB_PROFILE_DUAL_REPORT  2
#define PICADE_USB_PROFILE_DUAL_REPORT_CDC 3
#define PICADE_USB_PROFILE_HID_CDC      4

#ifndef PICADE_USB_PROFILE
#define PICADE_USB_PROFILE PICADE_USB_PROFILE_LEGACY
#endif

#if PICADE_USB_PROFILE == PICADE_USB_PROFILE_LEGACY
#define PICADE_USB_HID_INSTANCES 3
#define PICADE_USB_CDC_INSTANCES 1
#define PICADE_USB_HAS_KEYBOARD 1
#define PICADE_USB_HAS_CDC 1
#elif PICADE_USB_PROFILE == PICADE_USB_PROFILE_HID_ONLY
#define PICADE_USB_HID_INSTANCES 2
#define PICADE_USB_CDC_INSTANCES 0
#define PICADE_USB_HAS_KEYBOARD 0
#define PICADE_USB_HAS_CDC 0
#elif PICADE_USB_PROFILE == PICADE_USB_PROFILE_DUAL_REPORT
#define PICADE_USB_HID_INSTANCES 1
#define PICADE_USB_CDC_INSTANCES 0
#define PICADE_USB_HAS_KEYBOARD 0
#define PICADE_USB_HAS_CDC 0
#elif PICADE_USB_PROFILE == PICADE_USB_PROFILE_DUAL_REPORT_CDC
#define PICADE_USB_HID_INSTANCES 1
#define PICADE_USB_CDC_INSTANCES 1
#define PICADE_USB_HAS_KEYBOARD 0
#define PICADE_USB_HAS_CDC 1
#elif PICADE_USB_PROFILE == PICADE_USB_PROFILE_HID_CDC
#define PICADE_USB_HID_INSTANCES 2
#define PICADE_USB_CDC_INSTANCES 1
#define PICADE_USB_HAS_KEYBOARD 0
#define PICADE_USB_HAS_CDC 1
#else
#error Unknown PICADE_USB_PROFILE value
#endif

#if PICADE_USB_PROFILE == PICADE_USB_PROFILE_DUAL_REPORT || PICADE_USB_PROFILE == PICADE_USB_PROFILE_DUAL_REPORT_CDC
#define PICADE_USB_IS_DUAL_REPORT 1
#else
#define PICADE_USB_IS_DUAL_REPORT 0
#endif
